# Generated by Django 4.2.16 on 2024-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftsession',
            name='description',
            field=models.CharField(default='wqe', max_length=350),
            preserve_default=False,
        ),
    ]
