# Generated by Django 4.2.16 on 2025-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_store', '0002_giftsession_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsession',
            name='description',
            field=models.CharField(max_length=350, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='giftsession',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='giftsession',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
