# Generated by Django 4.2.16 on 2025-02-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0010_alter_customuser_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cabinet.survey')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.psychologistsurvey')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('time', models.TimeField(help_text='Время в формате HH:MM (от 00:00 до 23:00)')),
                ('is_available', models.BooleanField(default=True, help_text='Доступен ли слот для записи')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='cabinet.psychologistsurvey')),
            ],
            options={
                'ordering': ['day_of_week', 'time'],
                'unique_together': {('psychologist', 'day_of_week', 'time')},
            },
        ),
    ]
