# Generated by Django 4.2.16 on 2025-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'awaiting_payment'), ('cancelled', 'cancelled'), ('awaiting', 'awaiting'), ('complete', 'complete')], default='awaiting_payment', max_length=225),
        ),
    ]
