# Generated by Django 4.2.16 on 2025-02-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
