# Generated by Django 4.2.16 on 2024-12-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=550, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='answer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('author', models.CharField(max_length=125)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=550)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='article_covers/')),
                ('body', models.TextField()),
                ('age_restriction', models.PositiveIntegerField(blank=True, choices=[(18, '18+'), (16, '16+')], null=True)),
                ('release_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=550, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('answers', models.ManyToManyField(blank=True, to='wellness.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=550)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='test_covers/')),
                ('calculation', models.CharField(choices=[('position', 'По порядковому номеру ответов'), ('point', 'По баллам')], max_length=50)),
                ('questions', models.ManyToManyField(to='wellness.question')),
            ],
        ),
    ]
