# Generated by Django 4.2.16 on 2024-12-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='age_restriction',
            field=models.PositiveIntegerField(blank=True, choices=[(16, '16+'), (18, '18+')], null=True),
        ),
    ]
