# Generated by Django 4.2.16 on 2024-12-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='age_restriction',
            field=models.PositiveIntegerField(blank=True, choices=[(16, '16+'), (18, '18+')], null=True, verbose_name='Ограничение по возрасту'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.IntegerField(choices=[(3, 'Третий'), (1, 'Первый'), (2, 'Второй')], default=1, verbose_name='Тип теста'),
        ),
    ]
