# Generated by Django 4.2.16 on 2024-12-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0005_block_article_related_articles_remove_article_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_for_reading',
            field=models.CharField(default='15 минут', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='age_restriction',
            field=models.PositiveIntegerField(blank=True, choices=[(18, '18+'), (16, '16+')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('position', 'По порядковому номеру ответов'), ('point', 'По баллам')], max_length=50),
        ),
    ]
