# Generated by Django 4.2.16 on 2024-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0006_article_time_for_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_full_images/'),
        ),
    ]
