# Generated by Django 4.2.16 on 2024-12-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0009_alter_article_age_restriction_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('point', 'По баллам'), ('position', 'По порядковому номеру ответов')], max_length=50),
        ),
    ]
