# Generated by Django 4.2.16 on 2024-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0010_answer_points_alter_test_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_for_solving',
            field=models.CharField(default='20 минут', max_length=75),
        ),
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('position', 'По порядковому номеру ответов'), ('point', 'По баллам')], max_length=50),
        ),
    ]
