# Generated by Django 4.2.16 on 2024-12-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0011_test_time_for_solving_alter_test_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, max_length=275, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('point', 'По баллам'), ('position', 'По порядковому номеру ответов')], max_length=50),
        ),
    ]
