# Generated by Django 4.2.16 on 2024-12-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0013_test_full_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='age_restriction',
            field=models.PositiveIntegerField(blank=True, choices=[(18, '18+'), (16, '16+')], null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(),
        ),
    ]
