# Generated by Django 4.2.16 on 2024-12-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0014_alter_article_age_restriction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_created'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Количество баллов'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='age_restriction',
            field=models.PositiveIntegerField(blank=True, choices=[(18, '18+'), (16, '16+')], null=True, verbose_name='Ограничение по возрасту'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=125, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='wellness.block', verbose_name='Тело статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_full_images/', verbose_name='Полная картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, null=True, to='wellness.article', verbose_name='Похожие статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='release_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время выпуска статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_for_reading',
            field=models.CharField(max_length=150, verbose_name='Время на прочтение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=275, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, to='wellness.answer', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='result',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='result_covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=models.TextField(verbose_name='Оисание'),
        ),
        migrations.AlterField(
            model_name='result',
            name='max_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное кол-во очков'),
        ),
        migrations.AlterField(
            model_name='result',
            name='min_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное кол-во очков'),
        ),
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='result',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(max_length=275, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('position', 'По порядковому номеру ответов'), ('point', 'По баллам')], max_length=50, verbose_name='Подсчет'),
        ),
        migrations.AlterField(
            model_name='test',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='test_covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_full_images/', verbose_name='Полная картинка'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='wellness.question', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_for_solving',
            field=models.CharField(default='20 минут', max_length=75, verbose_name='Время на решение'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Название'),
        ),
    ]
