# Generated by Django 4.2.16 on 2024-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0017_alter_result_options_test_second_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('position', 'По порядковому номеру ответов'), ('point', 'По баллам')], max_length=50, verbose_name='Подсчет'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='wellness.question', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.IntegerField(choices=[(3, 'Третий'), (1, 'Первый'), (2, 'Второй')], default=1, verbose_name='Тип теста'),
        ),
    ]
