# Generated by Django 4.2.16 on 2024-12-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0018_alter_test_calculation_alter_test_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='age_restriction',
            field=models.PositiveIntegerField(blank=True, choices=[(18, '18+'), (16, '16+')], null=True, verbose_name='Ограничение по возрасту'),
        ),
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('point', 'По баллам'), ('position', 'По порядковому номеру ответов')], max_length=50, verbose_name='Подсчет'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='wellness.question', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.IntegerField(choices=[(2, 'Второй'), (3, 'Третий'), (1, 'Первый')], default=1, verbose_name='Тип теста'),
        ),
    ]
