# Generated by Django 4.2.16 on 2024-12-09 12:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0019_alter_article_age_restriction_alter_test_calculation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('position', 'По порядковому номеру ответов'), ('point', 'По баллам')], max_length=50, verbose_name='Подсчет'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='second_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание 2 (для тестов 3 типа)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.IntegerField(choices=[(2, 'Второй'), (1, 'Первый'), (3, 'Третий')], default=1, verbose_name='Тип теста'),
        ),
    ]
