# Generated by Django 4.2.16 on 2024-12-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0021_article_description_alter_article_age_restriction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='calculation',
            field=models.CharField(choices=[('point', 'По баллам'), ('position', 'По порядковому номеру ответов')], max_length=50, verbose_name='Подсчет'),
        ),
    ]
