# Generated by Django 4.2.16 on 2025-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0027_preferableprice_therapy_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychoTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
