# Generated by Django 4.2.16 on 2025-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0028_psychotopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='coupletherapy',
            options={'verbose_name': 'Парная терапия', 'verbose_name_plural': 'Парная терапия'},
        ),
        migrations.AlterModelOptions(
            name='feeling',
            options={'verbose_name': 'Мое состояние', 'verbose_name_plural': 'Мое состояние'},
        ),
        migrations.AlterModelOptions(
            name='lifeevent',
            options={'verbose_name': 'События в жизни', 'verbose_name_plural': 'События в жизни'},
        ),
        migrations.AlterModelOptions(
            name='preferableprice',
            options={'verbose_name': 'Предпочитаемая цена', 'verbose_name_plural': 'Предпочитаемые цены'},
        ),
        migrations.AlterModelOptions(
            name='psychotopic',
            options={'verbose_name': 'Психологическая тема', 'verbose_name_plural': 'Психологическые темы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'Отношения', 'verbose_name_plural': 'Отношения'},
        ),
        migrations.AlterModelOptions(
            name='workstudy',
            options={'verbose_name': 'Учеба и работа', 'verbose_name_plural': 'Учеба и работа'},
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=275, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='coupletherapy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lifeevent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='preferableprice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='preferableprice',
            name='experience',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='preferableprice',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='preferableprice',
            name='specialists_num',
            field=models.IntegerField(default=0, verbose_name='Количество специалистов'),
        ),
        migrations.AlterField(
            model_name='preferableprice',
            name='therapy_type',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Тип терапии'),
        ),
        migrations.AlterField(
            model_name='psychotopic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workstudy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
