# Generated by Django 4.2.16 on 2025-01-29 18:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0029_alter_answer_options_alter_block_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Название'),
        ),
    ]
