# Generated by Django 4.2.16 on 2025-02-03 09:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0030_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
