# Generated by Django 4.2.16 on 2025-02-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0031_alter_block_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scale',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (5, 'Пятый')], default=1, verbose_name='Тип теста'),
        ),
    ]
