# Generated by Django 4.2.16 on 2025-02-03 15:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0032_question_scale_alter_test_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
