# Generated by Django 4.2.16 on 2025-02-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0033_answer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Количество баллов'),
        ),
    ]
