# Generated by Django 4.2.16 on 2025-02-26 18:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0035_alter_answer_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField(blank=True)),
                ('answer', tinymce.models.HTMLField(blank=True)),
            ],
        ),
    ]
