# Generated by Django 4.2.16 on 2024-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_phoneverification_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
