# Generated by Django 4.2.16 on 2025-01-06 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_type', models.CharField(blank=True, max_length=225, null=True)),
                ('nickname', models.CharField(blank=True, max_length=225, null=True)),
                ('had_therapy_before', models.BooleanField(default=False)),
                ('date_of_birth', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('promo_code', models.CharField(blank=True, max_length=225, null=True)),
                ('feeling', models.CharField(blank=True, max_length=225, null=True)),
                ('relation', models.CharField(blank=True, max_length=225, null=True)),
                ('work_study', models.CharField(blank=True, max_length=225, null=True)),
                ('life_event', models.CharField(blank=True, max_length=225, null=True)),
                ('couple_therapy', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
