# Generated by Django 4.2.16 on 2025-01-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0027_preferableprice_therapy_type_and_more'),
        ('cabinet', '0005_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='preferable_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wellness.preferableprice'),
        ),
        migrations.RemoveField(
            model_name='survey',
            name='couple_therapy',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='life_event',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='work_study',
        ),
        migrations.AddField(
            model_name='survey',
            name='couple_therapy',
            field=models.ManyToManyField(blank=True, to='wellness.coupletherapy'),
        ),
        migrations.AddField(
            model_name='survey',
            name='feeling',
            field=models.ManyToManyField(blank=True, to='wellness.feeling'),
        ),
        migrations.AddField(
            model_name='survey',
            name='life_event',
            field=models.ManyToManyField(blank=True, to='wellness.lifeevent'),
        ),
        migrations.AddField(
            model_name='survey',
            name='relation',
            field=models.ManyToManyField(blank=True, to='wellness.relation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='work_study',
            field=models.ManyToManyField(blank=True, to='wellness.workstudy'),
        ),
    ]
