# Generated by Django 4.2.16 on 2025-01-08 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0028_psychotopic'),
        ('cabinet', '0006_survey_preferable_price_remove_survey_couple_therapy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('psychologist', 'psychologist')], default='psychologist', max_length=225),
        ),
        migrations.AlterField(
            model_name='survey',
            name='couple_therapy',
            field=models.ManyToManyField(blank=True, related_name='couple_therapy', to='wellness.coupletherapy'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='feeling',
            field=models.ManyToManyField(blank=True, related_name='feeling', to='wellness.feeling'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='life_event',
            field=models.ManyToManyField(blank=True, related_name='life_event', to='wellness.lifeevent'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='relation',
            field=models.ManyToManyField(blank=True, related_name='relation', to='wellness.relation'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='work_study',
            field=models.ManyToManyField(blank=True, related_name='work_study', to='wellness.workstudy'),
        ),
        migrations.CreateModel(
            name='PsychologistSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='psycho_avatars/')),
                ('education', models.TextField()),
                ('name', models.CharField(max_length=225)),
                ('experience', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('sex', models.CharField(choices=[('woman', 'woman'), ('man', 'man')], default='man', max_length=125)),
                ('psycho_topic', models.ManyToManyField(to='wellness.psychotopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psycho_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
