# Generated by Django 4.2.16 on 2025-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_education_remove_psychologistsurvey_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistsurvey',
            name='education_psychologist',
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='education_psychologist',
            field=models.ManyToManyField(blank=True, to='cabinet.education'),
        ),
    ]
