# Generated by Django 4.2.16 on 2025-01-13 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0029_alter_answer_options_alter_block_options_and_more'),
        ('cabinet', '0009_remove_psychologistsurvey_education_psychologist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-year'], 'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'verbose_name': 'Коды смс', 'verbose_name_plural': 'Коды смс'},
        ),
        migrations.AlterModelOptions(
            name='psychologistsurvey',
            options={'verbose_name': 'Психолог', 'verbose_name_plural': 'Психологи'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AlterField(
            model_name='education',
            name='text',
            field=models.TextField(verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.PositiveIntegerField(default=2000, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный код'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='education_psychologist',
            field=models.ManyToManyField(blank=True, to='cabinet.education', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='label',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='psycho_avatars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='psycho_topic',
            field=models.ManyToManyField(to='wellness.psychotopic', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='sex',
            field=models.CharField(choices=[('woman', 'Женский'), ('man', 'Мужской')], default='man', max_length=125, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psycho_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='couple_therapy',
            field=models.ManyToManyField(blank=True, related_name='couple_therapy', to='wellness.coupletherapy', verbose_name='Парная терапия'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='feeling',
            field=models.ManyToManyField(blank=True, related_name='feeling', to='wellness.feeling', verbose_name='Мое состояние'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='had_therapy_before',
            field=models.BooleanField(default=False, verbose_name='Был опыт терапии?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='life_event',
            field=models.ManyToManyField(blank=True, related_name='life_event', to='wellness.lifeevent', verbose_name='События в жизни'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='nickname',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='preferable_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wellness.preferableprice', verbose_name='Предпочитаемая цена'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='promo_code',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='relation',
            field=models.ManyToManyField(blank=True, related_name='relation', to='wellness.relation', verbose_name='Отношения'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='therapy_type',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Тип терапии'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='work_study',
            field=models.ManyToManyField(blank=True, related_name='work_study', to='wellness.workstudy', verbose_name='Учеба и работа'),
        ),
    ]
