# Generated by Django 4.2.16 on 2025-02-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_alter_customuser_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за сессию'),
        ),
    ]
