# Generated by Django 4.2.16 on 2025-02-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_psychologistsurvey_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='email',
            field=models.EmailField(blank=True, max_length=225, null=True),
        ),
    ]
