# Generated by Django 4.2.16 on 2025-02-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_psychologistsurvey_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='client_age',
            field=models.CharField(choices=[('16+', '16+'), ('18+', '18+')], default='18+', max_length=5),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='experience_with_identity_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='notifications_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='notifications_phone',
            field=models.BooleanField(default=False),
        ),
    ]
