# Generated by Django 4.2.16 on 2025-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_psychologistsurvey_client_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='language',
            field=models.CharField(default='Русский', max_length=155),
        ),
    ]
