# Generated by Django 4.2.16 on 2025-02-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_psychologistsurvey_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='couple_therapy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=225),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='working_methods',
            field=models.TextField(blank=True),
        ),
    ]
