# Generated by Django 4.2.16 on 2025-02-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_psychologistsurvey_couple_therapy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='session_duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Длительность сессии'),
        ),
    ]
