# Generated by Django 4.2.16 on 2025-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0017_psychologistsurvey_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
