# Generated by Django 4.2.16 on 2025-02-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0035_alter_answer_points'),
        ('cabinet', '0018_alter_psychologistsurvey_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='client_photos/'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='psychologistsurvey',
            name='psycho_topic',
            field=models.ManyToManyField(blank=True, to='wellness.psychotopic', verbose_name='Направление'),
        ),
    ]
