# Generated by Django 4.2.16 on 2025-02-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0019_survey_photo_alter_psychologistsurvey_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(max_length=19, verbose_name='Номер телефона'),
        ),
    ]
