# Generated by Django 4.2.16 on 2025-02-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0020_alter_phoneverification_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistsurvey',
            name='age',
        ),
    ]
