# Generated by Django 4.2.16 on 2025-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0022_education_diploma_psychologistsurvey_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='accepted_to_system',
            field=models.BooleanField(default=False, verbose_name='Подписан/а в Позитолк'),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='citizenship',
            field=models.CharField(blank=True, default='РФ', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='inn',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='tax_status',
            field=models.CharField(blank=True, choices=[('Самозанятый', 'Самозанятый'), ('ИП', 'ИП'), ('ООО', 'ООО'), ('АО', 'АО')], max_length=225, null=True),
        ),
    ]
