# Generated by Django 4.2.16 on 2025-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0023_psychologistsurvey_accepted_to_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
    ]
