# Generated by Django 4.2.16 on 2025-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0025_survey_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='date_of_birth_second',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='survey',
            name='message_notification',
            field=models.BooleanField(default=False, verbose_name='Уведомления о сообщении от терапевта'),
        ),
        migrations.AddField(
            model_name='survey',
            name='news_notification',
            field=models.BooleanField(default=False, verbose_name='Уведомления о новостях'),
        ),
        migrations.AddField(
            model_name='survey',
            name='nickname_second',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='survey',
            name='photo_second',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='client_photos/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='reminder_notification',
            field=models.BooleanField(default=False, verbose_name='Уведомления о встрече за 24 часа'),
        ),
    ]
