# Generated by Django 4.2.16 on 2025-02-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0026_survey_date_of_birth_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistsurvey',
            name='how_get_profession',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psychologistsurvey',
            name='your_values',
            field=models.TextField(blank=True),
        ),
    ]
